apiVersion: apps/v1
kind: Deployment
metadata:
  name: floci-cloud-lab-app
  namespace: floci-cloud-lab
  labels:
    app.kubernetes.io/name: floci-cloud-lab
    app.kubernetes.io/component: app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: floci-cloud-lab
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: floci-cloud-lab
        app.kubernetes.io/component: app
    spec:
      serviceAccountName: floci-cloud-lab-app
      automountServiceAccountToken: false
      containers:
        - name: app
          image: floci-cloud-lab-app:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: floci-cloud-lab-config
          env:
            - name: AWS_ACCESS_KEY_ID
              value: test
            - name: AWS_SECRET_ACCESS_KEY
              value: test
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
