apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: floci-cloud-lab-app-ingress
  namespace: floci-cloud-lab
  labels:
    app.kubernetes.io/name: floci-cloud-lab
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: floci-cloud-lab
      app.kubernetes.io/component: app
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
