apiVersion: v1
kind: Service
metadata:
  name: floci-cloud-lab-app
  namespace: floci-cloud-lab
  labels:
    app.kubernetes.io/name: floci-cloud-lab
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: floci-cloud-lab
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: http
